# Generated by Django 3.1 on 2023-08-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('is_scanned_for_virus', models.BooleanField(default=False)),
                ('is_duplicated', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_order', models.PositiveIntegerField(blank=True, default=0, null=True, unique=True)),
            ],
        ),
    ]
